export const iconsRecord: Record<string, string> = {
  pc: "Laptop",
  car: "Car",
  food: "Utensils",
  clothes: "Shirt",
  health: "Activity",
  education: "Book",
  travel: "Plane",
  entertainment: "Gamepad2",
  piggy: "PiggyBank",
  money: "DollarSign",
  card: "CreditCard",
  salary: "WalletMinimal",
  other: "CircleHelp",
};
